name: sentiment_analysis_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.5.2
    - pandas==2.2.3
    - numpy==2.1.3
    - joblib==1.4.2